AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ## S3 Buckets
  RawPhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mjburns-raw-photos"

  ProcessedPhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mjburns-processed-photos"

  ## Lambda Layer for pillow
  PillowLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MultiWatermarkLayer
      Description: "Lambda Layer for multiwatermark library"
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain

  ## Lambda Function for Image Processing
  PhotoProcessingLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PhotoProcessingFunction
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: photo_processing
      MemorySize: 512
      Timeout: 30
      Layers:
        - !Ref PillowLayer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref RawPhotosBucket
        - S3WritePolicy:
            BucketName: !Ref ProcessedPhotosBucket
      Environment:
        Variables:
          PROCESSED_BUCKET: !Ref ProcessedPhotosBucket

Outputs:
  RawPhotosBucketName:
    Description: "S3 bucket for raw photos"
    Value: !Ref RawPhotosBucket

  ProcessedPhotosBucketName:
    Description: "S3 bucket for processed photos"
    Value: !Ref ProcessedPhotosBucket

  LambdaFunctionArn:
    Description: "ARN of the Photo Processing Lambda function"
    Value: !GetAtt PhotoProcessingLambda.Arn
